name: Sync to Forked Repo

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Configure git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add fork as remote
        run: |
          git remote add fork https://${{secrets.JIWON_GITHUB_KEY}}@github.com/Choi-Jiwon-38/workinkorea.git
          git fetch fork
          git checkout develop

      - name: Push to forked repo
        run: |
          git push fork develop --force
