name: Sync to Foked Repo

on:
  push:
    branches:
      - main
      - develop

jobs:
  sync_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Push changes to personal repo
        run: |
          git remote add personal https://Choi-Jiwon-38:${{ secrets.JIWON_GITHUB_TOKEN }}@github.com/Choi-Jiwon-38/workinkorea.git
          git push personal ${{ github.ref }}:refs/heads/${{ github.ref_name }}
