name: Sync to Forked Repo

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.JIWON_GITHUB_KEY }}
          fetch-depth: 0
          ref: develop

      - name: Configure git
        run: |
          git remote add forked-repo https://Choi-Jiwon-38:${{ secrets.JIWON_GITHUB_KEY }}@github.com/Choi-Jiwon-38/workinkorea.git
          git config user.name "Choi-Jiwon-38"
          git config user.email "chlrhwldnjs@naver.com"

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo develop

      - name: Clean up
        run: |
          git remote remove forked-repo
